'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Answers', [
      {
        content: 'Web',
        path: "",
        value: 1800,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: 'Android',
        path: "",
        value: 1800,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: 'iOS',
        path: "",
        value: 1800,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: 'Web & Mobile (Android or iOS)',
        path: "",
        value: 3060,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: 'Web & Mobile (Android & iOS)',
        path: "",
        value: 3060,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: 'Simple user interface',
        path: "",
        value: 1200,
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: 'Custom interface',
        path: "",
        value: 3600,
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: 'Web replicated interface',
        path: "",
        value: 2400,
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "I don't need design",
        path: "",
        value: 0,
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Free app with ads",
        path: "",
        value: 150,
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Payment application",
        path: "",
        value: 150,
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "In-app purchase",
        path: "",
        value: 1200,
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Other / I don't know",
        path: "",
        value: 300,
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Yes, email and social network",
        path: "",
        value: 1200,
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Yes, with email",
        path: "",
        value: 750,
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "No",
        path: "",
        value: 0,
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "I don't know yet",
        path: "",
        value: 600,
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Yes",
        path: "",
        value: 1200,
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "No",
        path: "",
        value: 0,
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "I don't know",
        path: "",
        value: 600,
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Yes",
        path: "",
        value: 1200,
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "No",
        path: "",
        value: 0,
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "I don't know",
        path: "",
        value: 600,
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Yes",
        path: "",
        value: 1200,
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "No",
        path: "",
        value: 0,
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "I don't know",
        path: "",
        value: 600,
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Multilingual",
        path: "",
        value: 1200,
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Only one",
        path: "",
        value: 0,
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Bilingual",
        path: "",
        value: 600,
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "Yes",
        path: "",
        value: 0,
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "No",
        path: "",
        value: 0,
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "I don't know",
        path: "",
        value: 0,
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "0 - 3 months",
        path: "",
        value: 1.5,
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "4 - 6 months",
        path: "",
        value: 0,
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        content: "More than 6 months",
        path: "",
        value: 0,
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Answers', null, {});
  }
};
